mistakeDictionary = {
  'avove': 'above',
  'absense': 'absence',
  'accomodated': 'accommodated',
  'accomodate': 'accommodate',
  'accomodations': 'accommodations',
  'accomodation': 'accommodation',
  'acheived': 'achieved',
  'acheive': 'achieve',
  'accross': 'across',
  'agressive': 'aggressive',
  'agression': 'aggression',
  'apparantly': 'apparently',
  'appearences': 'appearances',
  'appearence': 'appearance',
  'arguements': 'arguments',
  'arguement': 'argument',
  'assasinations': 'assassinations',
  'assasination': 'assassination',
  'assasined': 'assassined',
  'assasin': 'assassin',
  'basicly': 'basically',
  'beginings': 'beginnings',
  'begining': 'beginning',
  'beleived': 'believed',
  'beleive': 'believe',
  'belived': 'believed',
  'belive': 'believe',
  'better then': 'better than',
  'bizzare': 'bizarre',
  'buisness': 'business',
  'calenders': 'calendars',
  'calender': 'calendar',
  'Carribean': 'Caribbean',
  'cemetaries': 'cemeteries',
  'cemetary': 'cemetery',
  'chasig': 'chasing',
  'chauffers': 'chauffeurs',
  'chauffer': 'chauffeur',
  'to chose': 'to choose',
  'coincidently': 'coincidentally',
  'collegues': 'colleagues',
  'collegue': 'colleague',
  'comming': 'coming',
  'commitees': 'committees',
  'commitee': 'committee',
  'completly': 'completely',
  'conciousness': 'consciousness',
  'concious': 'conscious',
  'curiousity': 'curiosity',
  'diffrent': 'different',
  'definately': 'definitely',
  'dilemnas': 'dilemmas',
  'dilemna': 'dilemma',
  'dissapeared': 'disappeared',
  'dissapears': 'disappeare',
  'dissapear': 'disappear',
  'dissapointed': 'disappointed',
  'dissapoint ': 'disappoint ',
  'dissapoint.': 'disappoint.',
  'dissapointing': 'disappointing',
  'ecstacy': 'ecstasy',
  'embarassment': 'embarrassment',
  'embarassed': 'embarrassed',
  'embarassing': 'embarrassing',
  'embarass': 'embarrass',
  'enviroment': 'environment',
  'essense': 'essence',
  'Etherium': 'Ethereum',
  'Ethetum': 'Ethereum',
  'existance': 'existence',
  'farenheit': 'fahrenheit',
  'familar': 'familiar',
  'filosophy': 'philosophy',
  'finaly': 'finally',
  'fith': 'with',
  'florescent': 'fluorescent',
  'foriegn': 'foreign',
  'forseeable': 'foreseeable',
  'fourty': 'forty',
  'foward': 'forward',
  'freindship': 'friendship',
  'freinds': 'friends',
  'freind': 'friend',
  'futher': 'further',
  'jist': 'gist',
  'glamourous': 'glamorous',
  'goverment': 'government',
  'gaurd': 'guard',
  'it happend': 'it happened',
  'let this happend': 'let this happen',
  'may happend': 'may happen',
  'to happend': 'to happen',
  'that happend': 'that happened',
  'what happend': 'what happened',
  'which happend': 'which happened',
  'happends': 'happens',
  'harrass': 'harass',
  'harrassment': 'harassment',
  'honourary': 'honorary',
  'humourous': 'humorous',
  'idiosyncracy': 'idiosyncrasy',
  'immediatly': 'immediately',
  'incidently': 'incidentally',
  'in the long term,': 'in the long run,',
  'independant': 'independent',
  'interupt': 'interrupt',
  'irresistable': 'irresistible',
  'it\'s own': 'its own',
  'knowlege': 'knowledge',
  'liase': 'liaise',
  'liason': 'liaison',
  'lollypop': 'lollipop',
  'maintainance': 'maintenance',
  'millenium': 'millennium',
  'millenials': 'millennials',
  'millenial': 'millennial',
  'millenia': 'millennia',
  'miniscule': 'minuscule',
  'mispell': 'misspell',
  'neandertal': 'neanderthal',
  'neborn': 'newborn',
  'neccessary': 'necessary',
  'necesary': 'necessary',
  'neccesary': 'necessary',
  'noticable': 'noticeable',
  'ocassionally': 'occasionally',
  'occassionally': 'occasionally',
  'ocassions': 'occasions',
  'ocassion': 'occasion',
  'occassions': 'occasions',
  'occassion': 'occasion',
  'occured': 'occurred',
  'occuring': 'occurring',
  'occurances': 'occurrences',
  'occurance': 'occurrence',
  'occurences': 'occurrences',
  'occurence': 'occurrence',
  'on of the': 'one of the',
  'otder': 'order',
  'our of': 'out of',
  'pavillion': 'pavilion',
  'people which': 'people who',
  'people wich': 'people who',
  'persistant': 'persistent',
  'pharoah': 'pharaoh',
  'peices': 'pieces',
  'peice': 'piece',
  'politican': 'politician',
  'Portugese': 'Portuguese',
  'posession': 'possession',
  'prefering': 'preferring',
  'prefered': 'preferred',
  'presense': 'presence',
  'pronounciation': 'pronunciation',
  'propoganda': 'propaganda',
  'publically': 'publicly',
  'realy': 'really',
  'recieved': 'received',
  'recieve': 'receive',
  'refered': 'referred',
  'refering': 'referring',
  'refridgerator': 'refrigerator',
  'regaurding': 'regarding',
  'rejistered': 'registered',
  'rejister': 'register',
  'religous': 'religious',
  'rember': 'remember',
  'remeber': 'remember',
  'resistence': 'resistance',
  'sandwhich': 'sandwich',
  'sandwitch': 'sandwich',
  'schedual': 'schedule',
  'scedule': 'schedule',
  'I\'ve seem': 'I\'ve seen',
  'I have seem': 'I have seen',
  'sence': 'sense',
  'seperately': 'separately',
  'seperated': 'separated',
  'seperate': 'separate',
  'seperates': 'separates',
  'seige': 'siege',
  'sencond': 'second',
  'senconds': 'seconds',
  'sever pain': 'severe pain',
  'sneak peak': 'sneak peek',
  'speshul': 'special',
  'Stremit': 'Steemit',
  'succesfully': 'successfully',
  'succesful': 'successful',
  'supercede': 'supersede',
  'suprised': 'surprised',
  'suprise': 'surprise',
  'tatoo': 'tattoo',
  'there own': 'their own',
  'thet': 'they',
  'they\'re own': 'their own',
  'thier': 'their',
  'tendancy': 'tendency',
  'therefor': 'therefore',
  'threshhold': 'threshold',
  'tommorow': 'tomorrow',
  'tommorrow': 'tomorrow',
  'toung': 'tongue',
  'tounge': 'tongue',
  'truely': 'truly',
  'unatractive': 'unattractive',
  'unecessary': 'unnecessary',
  'unforseen': 'unforeseen',
  'unfortunatly': 'unfortunately',
  'untill': 'until',
  'velong': 'belong',
  'velonging': 'belonging',
  'veternary': 'veterinary',
  'wierder': 'weirder',
  'wierdo': 'weirdo',
  'wierd': 'weird',
  'whereever': 'wherever',
  'whic': 'which',
  'wich': 'which',
  'without further adieu': 'without further ado',
  'without further due': 'without further ado',
  'works really good': 'works really well',
  'your a': 'you\'re a',
  'your the': 'you\'re the',
}

function correctText(text, mistakeDictionary) {
  const alphaNumerical = char => 'abcdefghijklmnopqrstuvwxyz1234567890'.indexOf(char) === -1 ? false : true;
  let lowerText = text.toLowerCase();
  let fixedText = text;
  for (let mistake of Object.keys(mistakeDictionary)) {
    let mistakeIndex = lowerText.indexOf(mistake.toLowerCase());
    if (mistakeIndex !== -1 && (mistakeIndex-1 < 0 || !alphaNumerical(lowerText.charAt(mistakeIndex-1))) && (mistakeIndex+mistake.length === lowerText.length || !alphaNumerical(lowerText.charAt(mistakeIndex+mistake.length)))) {
      fixedText = fixedText.substr(0, mistakeIndex) + '<span title="suggestion: ' + mistakeDictionary[mistake] + '" style="color:red">' + fixedText.substr(mistakeIndex, mistake.length) + '</span>' + fixedText.substring(mistakeIndex + mistake.length);
      lowerText = fixedText.toLowerCase();
    }
  }
  return fixedText;
}